"""
Case report generation.
Each alert/email gets its own Markdown report; an index file links them all.
"""

import os
from datetime import datetime, timezone

import config


def _now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _safe_id(raw_id: str) -> str:
    return "".join(c if c.isalnum() or c in "-_" else "_" for c in str(raw_id))


def write_log_alert_report(alert: dict, findings: dict) -> str:
    """Write a case report for a single SIEM/log alert. Returns the file path."""
    os.makedirs(config.REPORTS_DIR, exist_ok=True)
    case_id = _safe_id(alert.get("alert_id", datetime.now().timestamp()))
    path = os.path.join(config.REPORTS_DIR, f"case_{case_id}.md")

    lines = [
        f"# Case Report — Alert {alert.get('alert_id', 'UNKNOWN')}",
        "",
        f"**Generated:** {_now()}  ",
        f"**Type:** Log/SIEM Alert  ",
        f"**Severity:** {findings['severity']}  ",
        f"**Risk Score:** {findings['score']}",
        "",
        "## Original Alert Details",
        "",
        f"- **Timestamp:** {alert.get('timestamp', 'N/A')}",
        f"- **Source:** {alert.get('source', 'N/A')}",
        f"- **Event Type:** {alert.get('event_type', 'N/A')}",
        f"- **User:** {alert.get('user', 'N/A')}",
        f"- **Source IP:** {alert.get('src_ip', 'N/A')}",
        f"- **Destination IP:** {alert.get('dst_ip', 'N/A')}",
        f"- **Description:** {alert.get('description', 'N/A')}",
        "",
        "## Analysis Findings",
        "",
    ]
    for ind in findings["indicators"]:
        lines.append(f"- {ind}")

    lines += [
        "",
        "## Recommended Next Steps",
        "",
        _recommend(findings["severity"]),
        "",
        "---",
        "*Auto-generated by SOC L1 Alert Monitoring Tool — review before escalation.*",
    ]

    with open(path, "w") as f:
        f.write("\n".join(lines))

    _append_index(case_id, "Log Alert", alert.get("description", "")[:80], findings["severity"], path)
    return path


def write_email_report(eml_path: str, findings: dict) -> str:
    """Write a case report for an analyzed email. Returns the file path."""
    os.makedirs(config.REPORTS_DIR, exist_ok=True)
    case_id = _safe_id(os.path.splitext(os.path.basename(eml_path))[0])
    path = os.path.join(config.REPORTS_DIR, f"case_email_{case_id}.md")
    meta = findings["meta"]

    lines = [
        f"# Case Report — Email {os.path.basename(eml_path)}",
        "",
        f"**Generated:** {_now()}  ",
        f"**Type:** Suspicious Email / Attachment  ",
        f"**Severity:** {findings['severity']}  ",
        f"**Risk Score:** {findings['score']}",
        "",
        "## Email Details",
        "",
        f"- **From:** {meta.get('from', 'N/A')}",
        f"- **Reply-To:** {meta.get('reply_to', 'N/A') or 'N/A'}",
        f"- **Subject:** {meta.get('subject', 'N/A')}",
        f"- **Attachments:** {', '.join(meta.get('attachments', [])) or 'None'}",
        f"- **URLs found:** {', '.join(meta.get('urls', [])) or 'None'}",
        "",
        "## Analysis Findings",
        "",
    ]
    for ind in findings["indicators"]:
        lines.append(f"- {ind}")

    lines += [
        "",
        "## Recommended Next Steps",
        "",
        _recommend(findings["severity"]),
        "",
        "---",
        "*Auto-generated by SOC L1 Alert Monitoring Tool — review before escalation.*",
    ]

    with open(path, "w") as f:
        f.write("\n".join(lines))

    _append_index(case_id, "Email", meta.get("subject", "")[:80], findings["severity"], path)
    return path


def _recommend(severity: str) -> str:
    return {
        "Critical": "Escalate to L2/IR immediately. Isolate affected host/mailbox. Preserve evidence.",
        "High": "Escalate to L2 for validation within SLA. Consider containment of affected asset.",
        "Medium": "Investigate further; correlate with related alerts. Escalate if pattern confirmed.",
        "Low": "Log for trend analysis. No immediate action unless part of a larger pattern.",
    }.get(severity, "Manual review recommended.")


def _append_index(case_id, case_type, summary, severity, path):
    os.makedirs(config.REPORTS_DIR, exist_ok=True)
    is_new = not os.path.exists(config.INDEX_FILE)
    with open(config.INDEX_FILE, "a") as f:
        if is_new:
            f.write("# SOC Case Report Index\n\n")
            f.write("| Case ID | Type | Severity | Summary | Report |\n")
            f.write("|---|---|---|---|---|\n")
        f.write(f"| {case_id} | {case_type} | {severity} | {summary} | [{os.path.basename(path)}]({os.path.basename(path)}) |\n")
